### ISSUE TITLE
Crash on server [1.19.2]

### ISSUE THREAD

**Issue by gamerpotion** [kittech0/Ventur#2]
Hi, im using this on our modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg

on our official server, I noticed from the logs we had a few crashes (log below). It seemed to interfere with the BYG biomes mod?

```---- Minecraft Crash Report ----
// There are four lights!

Time: 2022-10-05 23:48:24
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot set property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]} as it does not exist in Block{byg:embur_roots}
	at net.minecraft.class_2688.method_11657(class_2688.java:117)
	at net.minecraft.class_2320.method_10021(class_2320.java:79)
	at potionstudios.byg.common.block.nether.embur.EmburPlantBlock.method_9652(EmburPlantBlock.java:39)
	at net.minecraft.class_1752.method_7720(class_1752.java:74)
	at io.github.justfoxx.venturorigin.powers.OverGrown.bonemeal(OverGrown.java:29)
	at io.github.justfoxx.venturorigin.powers.OverGrown.function(OverGrown.java:63)
	at io.github.justfoxx.venturorigin.powers.OverGrown.tick(OverGrown.java:47)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_3222_1356f9d8.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zlm000$tick(class_3218.java:5726)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:117)
	at net.minecraft.class_2320.method_10021(class_2320.java:79)
	at potionstudios.byg.common.block.nether.embur.EmburPlantBlock.method_9652(EmburPlantBlock.java:39)
	at net.minecraft.class_1752.method_7720(class_1752.java:74)
	at io.github.justfoxx.venturorigin.powers.OverGrown.bonemeal(OverGrown.java:29)
	at io.github.justfoxx.venturorigin.powers.OverGrown.function(OverGrown.java:63)
	at io.github.justfoxx.venturorigin.powers.OverGrown.tick(OverGrown.java:47)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_3222_1356f9d8.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zlm000$tick(class_3218.java:5726)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 155082
	Entity Name: Berrymuffin97
	Entity's Exact location: 3045.96, 42.00, -3992.52
	Entity's Block location: World: (3045,42,-3993), Section: (at 5,10,7 in 190,2,-250; chunk contains blocks 3040,0,-4000 to 3055,255,-3985), Region: (5,-8; contains chunks 160,-256 to 191,-225, blocks 2560,0,-4096 to 3071,255,-3585)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by kittech0** [comment]
BYG issues

**Comment by kittech0** [comment]
Fixed
https://github.com/AOCAWOL/BYG/commit/11904b8134c55761bcd4f525d68a470c58acdaa1

**Comment by gamerpotion** [comment]
hi, it seems this issue is still occuring even with the new BYG update. 2 server crash reports below.

```---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2022-10-16 16:35:32
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot set property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]} as it does not exist in Block{byg:thereal_bellflower}
	at net.minecraft.class_2688.method_11657(class_2688.java:117)
	at net.minecraft.class_2320.method_10021(class_2320.java:79)
	at potionstudios.byg.common.block.end.EtherPlantBlock.method_9652(EtherPlantBlock.java:60)
	at net.minecraft.class_1752.method_7720(class_1752.java:74)
	at io.github.justfoxx.venturorigin.powers.OverGrown.bonemeal(OverGrown.java:29)
	at io.github.justfoxx.venturorigin.powers.OverGrown.function(OverGrown.java:63)
	at io.github.justfoxx.venturorigin.powers.OverGrown.tick(OverGrown.java:47)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zko000$tick(class_3218.java:4726)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.redirect$bjk000$catchExceptions(MinecraftServer.java:6782)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zme000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:117)
	at net.minecraft.class_2320.method_10021(class_2320.java:79)
	at potionstudios.byg.common.block.end.EtherPlantBlock.method_9652(EtherPlantBlock.java:60)
	at net.minecraft.class_1752.method_7720(class_1752.java:74)
	at io.github.justfoxx.venturorigin.powers.OverGrown.bonemeal(OverGrown.java:29)
	at io.github.justfoxx.venturorigin.powers.OverGrown.function(OverGrown.java:63)
	at io.github.justfoxx.venturorigin.powers.OverGrown.tick(OverGrown.java:47)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zko000$tick(class_3218.java:4726)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.redirect$bjk000$catchExceptions(MinecraftServer.java:6782)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 103991
	Entity Name: SeleneGoldFlame
	Entity's Exact location: 755.39, 58.00, 2078.66
	Entity's Block location: World: (755,58,2078), Section: (at 3,10,14 in 47,3,129; chunk contains blocks 752,0,2064 to 767,255,2079), Region: (1,4; contains chunks 32,128 to 63,159, blocks 512,0,2048 to 1023,255,2559)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.redirect$bjk000$catchExceptions(MinecraftServer.java:6782)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zme000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 4 total; [class_3222['NuclearJack18'/386, l='ServerLevel[world]', x=435.98, y=122.00, z=2363.63], class_3222['SeleneGoldFlame'/103991, l='ServerLevel[world]', x=755.39, y=58.00, z=2078.66], class_3222['Predator360x'/562, l='ServerLevel[world]', x=7888.20, y=55.00, z=-5759.86], class_3222['exitente'/191, l='ServerLevel[world]', x=93.09, y=60.21, z=-50.93]]
	Chunk stats: 5742
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (47,63,244), Section: (at 15,15,4 in 2,3,15; chunk contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2004127 game time, 2004127 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zme000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)```

---------------------------------------------------------------------

```---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2022-10-16 16:39:36
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot set property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]} as it does not exist in Block{byg:ether_grass}
	at net.minecraft.class_2688.method_11657(class_2688.java:117)
	at net.minecraft.class_2320.method_10021(class_2320.java:79)
	at potionstudios.byg.common.block.end.EtherPlantBlock.method_9652(EtherPlantBlock.java:60)
	at net.minecraft.class_1752.method_7720(class_1752.java:74)
	at io.github.justfoxx.venturorigin.powers.OverGrown.bonemeal(OverGrown.java:29)
	at io.github.justfoxx.venturorigin.powers.OverGrown.function(OverGrown.java:63)
	at io.github.justfoxx.venturorigin.powers.OverGrown.tick(OverGrown.java:47)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zko000$tick(class_3218.java:4726)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.redirect$bjk000$catchExceptions(MinecraftServer.java:6782)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zme000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:117)
	at net.minecraft.class_2320.method_10021(class_2320.java:79)
	at potionstudios.byg.common.block.end.EtherPlantBlock.method_9652(EtherPlantBlock.java:60)
	at net.minecraft.class_1752.method_7720(class_1752.java:74)
	at io.github.justfoxx.venturorigin.powers.OverGrown.bonemeal(OverGrown.java:29)
	at io.github.justfoxx.venturorigin.powers.OverGrown.function(OverGrown.java:63)
	at io.github.justfoxx.venturorigin.powers.OverGrown.tick(OverGrown.java:47)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zko000$tick(class_3218.java:4726)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.redirect$bjk000$catchExceptions(MinecraftServer.java:6782)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 8189
	Entity Name: SeleneGoldFlame
	Entity's Exact location: 755.39, 58.00, 2078.66
	Entity's Block location: World: (755,58,2078), Section: (at 3,10,14 in 47,3,129; chunk contains blocks 752,0,2064 to 767,255,2079), Region: (1,4; contains chunks 32,128 to 63,159, blocks 512,0,2048 to 1023,255,2559)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.redirect$bjk000$catchExceptions(MinecraftServer.java:6782)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zme000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 4 total; [class_3222['exitente'/266, l='ServerLevel[world]', x=73.53, y=230.38, z=-2851.13], class_3222['NuclearJack18'/278, l='ServerLevel[world]', x=170.20, y=70.70, z=2111.82], class_3222['Predator360x'/1901, l='ServerLevel[world]', x=7824.88, y=57.29, z=-5765.76], class_3222['SeleneGoldFlame'/8189, l='ServerLevel[world]', x=755.39, y=58.00, z=2078.66]]
	Chunk stats: 4587
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (47,63,244), Section: (at 15,15,4 in 2,3,15; chunk contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2006425 game time, 2006425 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zme000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)```
